### PR TITLE
gulp4 ready and include/exclude options

### PR DESCRIPTION
**Pull request by warmrobot**
- There some extra diffs in readme, because some space on empty lines were removed.

### CODE REVIEW

**Comment by slavafomin** [comment]
Thank you Igor for your hard work! I'm a bit overwhelmed right now with all the tasks at my hands. I will try to look at this when time permits.

**Comment by slavafomin** [comment]
I'm really sorry @warmrobot, I still can't divert any attention here at the time being.

**Comment by kapooostin** [comment]
+1

**Comment by Firanolfind** [comment]
+1

**Comment by Firanolfind** [comment]
Would there be support for Gulp4?

**Comment by slavafomin** [comment]
I'm so sorry, but this extension is [deprecated](https://github.com/betsol/gulp-require-tasks#deprecation-notice) and archived now. You can still use it in legacy projects with **Gulp 3**, but I'm not planning to fix the issues or add new features, as well as merging any PRs.

🚀 Please, consider migrating to [Gulp 4][gulp-4] with [Gulp Hub][gulp-hub] instead.

❤️ Thank you for using this library in the past. I wish you the best of luck with your projects!

  [gulp-4]:   https://gulpjs.com/
  [gulp-hub]: https://github.com/frankwallis/gulp-hub/tree/registry-init

**Pull request closed without merging**
